#!/bin/bash

export SAGA_INSTALL_DIR=${SAGA_INSTALL_DIR:-$HOME/GEMAUT/saga_install}
export GEMAUT_INSTALL_DIR=${GEMAUT_INSTALL_DIR:-$HOME/GEMAUT/GEMO}

export LD_LIBRARY_PATH=$SAGA_INSTALL_DIR/lib:$CONDA_PREFIX/lib:$LD_LIBRARY_PATH
export PROJ_LIB=$CONDA_PREFIX/share/proj
export PATH=$SAGA_INSTALL_DIR/bin:$GEMAUT_INSTALL_DIR/bin:$PATH

echo "GEMAUT and SAGA environment activated."
