input:
  mns_file: /chemin/vers/MNS.tif
  mask_file: null
  init_file: null
  output_file: /chemin/vers/MNT.tif
  work_dir: /chemin/vers/RepTra
processing:
  resolution: 4.0
  cpu_count: 8
  clean_temp: false
  verbose: false
gemo:
  sigma: 0.5
  regul: 0.01
  norme: hubertukey
tiling:
  tile_size: 300
  pad_size: 120
nodata:
  external: -32768
  internal: -32767
mask:
  ground_value: 0
saga:
  radius: 100
  tile: 100
  pente: 15
