# Configuration GEMAUT pour votre traitement
# Correspond à: script_gemaut --mns /Volumes/DANI/data_nchampion/DATA_TEST_GEMO/IN/FusionPNEO_CROP_XS.tif --out /Volumes/ESPACE_TRAVAIL/DANI/data_nchampion/DATA_PNEO/DATA_MTPL/DATA_CURSOR/out_TEST.tif --reso 4 --cpu 8 --RepTra RepTraVerif --nodata_ext -32768 --nodata_int -32767 --groundval 0

# Paramètres d'entrée/sortie
input:
  mns_file: "/Volumes/DANI/data_nchampion/DATA_TEST_GEMO/IN/FusionPNEO_CROP_XS.tif"
  mask_file: null  # null pour calcul automatique avec SAGA
  init_file: null  # null pour utiliser le MNS
  output_file: "/Volumes/ESPACE_TRAVAIL/DANI/data_nchampion/DATA_PNEO/DATA_MTPL/DATA_CURSOR/out_TEST_YAML.tif"
  work_dir: "RepTraVerif"

# Paramètres de traitement
processing:
  resolution: 4.0
  cpu_count: 8
  clean_temp: false
  verbose: false

# Paramètres GEMO (valeurs par défaut)
gemo:
  sigma: 0.5
  regul: 0.01
  norme: "hubertukey"

# Paramètres de tuilage (valeurs par défaut)
tiling:
  tile_size: 300
  pad_size: 120

# Paramètres NoData (spécifiés dans votre commande)
nodata:
  external: -32768
  internal: -32767

# Paramètres masque (spécifié dans votre commande)
mask:
  ground_value: 0

# Paramètres SAGA (pour calcul automatique du masque)
saga:
  radius: 100
  tile: 100
  pente: 15 
