# Configuration GEMAUT pour test de compatibilité MNS/Masque
# Basé sur config_ground_mask_csf.SOUSRESOLU.ini

# Paramètres d'entrée/sortie
input:
  mns_file: "/Volumes/DANI/data_nchampion/DATA_TEST_GEMO/IN/FusionPNEO_CROP_XS.tif"
  mask_file: "/home/NChampion/DATADRIVE1/DEVELOPPEMENT/test_cursor/GEMAUT-pipeline/tests/pdal_ground_mask_strict.SOUSRESOLU.tif"
  init_file: null
  output_file: "/home/NChampion/DATADRIVE1/DEVELOPPEMENT/test_cursor/GEMAUT-pipeline/tests/MNT_OUT_TEST_ground_mask_csf.SOUSRESOLU.tif"
  work_dir: "./RepTra_tmp_20250822"

# Paramètres de traitement
processing:
  resolution: 4.0
  cpu_count: 8
  clean_temp: false
  verbose: true

# Paramètres GEMO
gemo:
  sigma: 0.5
  regul: 0.01
  norme: "hubertukey"

# Paramètres de tuilage
tiling:
  tile_size: 300
  pad_size: 120

# Paramètres NoData
nodata:
  external: -32768
  internal: -32767

# Paramètres masque
mask:
  ground_value: 0

# Paramètres SAGA
saga:
  radius: 100
  tile: 100
  pente: 15 