# Configuration GEMAUT - Template
# Copiez ce fichier en config.yaml et modifiez les valeurs selon vos besoins

# Paramètres d'entrée/sortie
input:
  mns_file: "/chemin/vers/MNS.tif"
  mask_file: null  # null pour calcul automatique avec SAGA
  init_file: null  # null pour utiliser le MNS
  output_file: "/chemin/vers/MNT.tif"
  work_dir: "/chemin/vers/RepTra"

# Paramètres de traitement
processing:
  resolution: 4.0
  cpu_count: 8
  clean_temp: false
  verbose: false

# Paramètres GEMO
gemo:
  sigma: 0.5
  regul: 0.01
  norme: "hubertukey"

# Paramètres de tuilage
tiling:
  tile_size: 300
  pad_size: 120

# Paramètres NoData
nodata:
  external: -32768
  internal: -32767

# Paramètres masque
mask:
  ground_value: 0

# Paramètres SAGA (pour calcul automatique du masque)
saga:
  radius: 100
  tile: 100
  pente: 15 